### ISSUE TITLE
NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractContainerRequestValueFactory

### ISSUE THREAD

**Issue by ngton** [pac4j/dropwizard-pac4j#53]
Updating to the latest dropwizard-pac4j, I'm getting this runtime error. I can't work out what dependency I need to add. Please can you help?

I'm currently using jersey-server 2.31

`java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractContainerRequestValueFactory
        at org.pac4j.jax.rs.jersey.features.Pac4JValueFactoryProvider$Binder.<init>(Pac4JValueFactoryProvider.java:169)
        at org.pac4j.jax.rs.jersey.features.Pac4JValueFactoryProvider$Binder.<init>(Pac4JValueFactoryProvider.java:153)
        at org.pac4j.dropwizard.Pac4jBundle.run(Pac4jBundle.java:98)
        at org.pac4j.dropwizard.Pac4jBundle.run(Pac4jBundle.java:35)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
`

**Comment by leleuj** [comment]
You should use the `jersey-pac4j` dependency.
